[package]
name = "redis"
version = "0.1.0"
edition = "2024"


[dependencies]
socket2 = "=0.6.0"
errno = "0.3"
nix = { version = "0.27.0", features = ["poll"] }
intrusive-collections = "=0.9.6"
ordered-float = "4"
